// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIkqUknnX95m-DES6cRH1QFGv6gPmMB9U',
    appId: '1:572134187829:web:d8fb0fb599133f3e7ce27c',
    messagingSenderId: '572134187829',
    projectId: 'task-management-thiran',
    authDomain: 'task-management-thiran.firebaseapp.com',
    storageBucket: 'task-management-thiran.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsm5ymDVoi0gIy5A3NgrgOInbwry5IBns',
    appId: '1:572134187829:android:dcc3c94282b212847ce27c',
    messagingSenderId: '572134187829',
    projectId: 'task-management-thiran',
    storageBucket: 'task-management-thiran.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQps2RZapOhsOYfltrF-YFnISY6c5mX5U',
    appId: '1:572134187829:ios:542597d5fa39fe227ce27c',
    messagingSenderId: '572134187829',
    projectId: 'task-management-thiran',
    storageBucket: 'task-management-thiran.firebasestorage.app',
    iosBundleId: 'com.keerthi77459.taskAutomationAndManagementSystem',
  );
}
